#+PROPERTY: HEADER-ARGS+ :eval never-export
#+TITLE: F4ncgb

* Compiling

Please use [[https://cmake.org/][CMake]] to compile this project:

#+BEGIN_SRC bash :export both
git clone https://gitlab.sai.jku.at/f4ncgb/f4ncgb.git
mkdir build-release
cd build-release
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j
#+END_SRC

Then, ~f4ncgb~, ~f4ncgb_test~, and ~mod_prime_tester~ are produced.

* Usage

** F4NCGB

#+BEGIN_SRC bash :export both
./f4ncgb <input.ms>
#+END_SRC


** F4NCGB Test

#+BEGIN_SRC bash :export both
./f4ncgb_test
#+END_SRC

This should produce the following output:

: Running 12 test cases...
:  
: *** No errors detected

Internally, the tests also create our store structure multiple times
and test the memory allocation to fit our requirements.

** Mod Prime Tester

Run the exhaustive tests:

#+BEGIN_SRC bash :export both
./mod_prime_tester -t
#+END_SRC

The tests output three columns: ~test~, the highest number tested (up
to the given prime number), and the time (in seconds). Each
calculation is checked against the standard modulo operation. Below is
an example output using GCC 15.1 on Fedora 42 on an Intel i7-10700
CPU.

#+BEGIN_EXAMPLE
test			2147483647	0.924757
#+END_EXAMPLE

Run the benchmarks:

#+BEGIN_SRC bash :export both
./mod_prime_tester -b
#+END_SRC

The benchmark output three rows: The variant (the standard modulo, the
optimized variant using the mersenne prime $2^31-1$, and a modulo
power-of-two variant as "upper limit" of our mersenne-optimization, as
the compiler can optimize a modulo power-of-two into a bitmask). The
columns are (as in the test) the highest number tested, the time (in
seconds) for each run, and (for the optimized variant), the speedup
compared to the standard modulo. Below is an example output using GCC
15.1 on Fedora 42 on an Intel i7-10700 CPU.

#+BEGIN_EXAMPLE
benchmark-standard	2147483647	3.685986
benchmark-optimized	2147483647	0.461233	7.991587
benchmark-power-of-two	2147483647	0.464492
#+END_EXAMPLE

Some examples of the Mersenne Prime optimization speedups with
different compilers and processors, each tuned to the native
instruction set level using ~-march=native~ can be seen in the table
below. We sorted the table according to the achieved speedup. While
the optimized variant is slower for Clang, GCC produces binaries that
overall are faster than the ones from Clang.

| CPU                   | Compiler                               | Standard [s] | Optimized [s] | Speedup [Standard/Optimized] |
|-----------------------+----------------------------------------+--------------+---------------+------------------------------|
| AMD EPYC 7443P        | GCC Ubuntu 13.3.0                      |     3.221571 |      0.268126 |                    12.015138 |
| Intel i7-10700        | GCC 15.1.1 20250425 (Red Hat 15.1.1-1) |     3.681353 |      0.459711 |                    8.0079724 |
| Intel Xeon w5-2455X   | GCC Ubuntu 13.3.0                      |     2.945403 |      0.492927 |                    5.9753331 |
| Intel Xeon w5-2455X   | Clang 18.1.3 (1ubuntu1)                |     0.445653 |      0.732898 |                   0.60806961 |
| Intel i7-10700        | Clang 20.1.3 (Fedora 20.1.3-1.fc42)    |     0.459104 |      0.954247 |                   0.48111652 |
| MacBookAir M2 (ARM64) | AppleClang 16                          |     0.641846 |      1.404497 |                   0.45699350 |
| AMD EPYC 7443P        | Clang 18.1.3 (1ubuntu1)                |     0.268077 |      0.898394 |                   0.29839580 |
#+TBLFM: $5=$3/$4
